# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30)),
                ('card_cooperation', models.CharField(max_length=50)),
                ('card_balance', models.FloatField()),
                ('card_kind', models.CharField(max_length=20)),
                ('card_date', models.DateField()),
            ],
        ),
    ]
